version: 0.0
os: linux
files:
  - source: spring-mvc-demo-0.0.1-SNAPSHOT.war
    destination: /var/lib/tomcat7/webapps/
  - source: scripts
    destination: /tmp
hooks:
  BeforeInstall:
    - location: tomcat_stop.sh
      timeout: 300
      runas: root
#  AfterInstall:
#    - location: afterinstall.sh
#      timeout: 300
#      runas: root
  ApplicationStart:
    - location: tomcat_start.sh
      timeout: 300
      runas: root
