version: 0.2

phases:
  install:
    commands:
      - apt-get update -y
      - apt-get install -y maven
  pre_build:
    commands:
      - echo Pre Build on `date`
  build:
    commands:
      - echo Build started on `date`
      - mvn package 
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/spring-mvc-demo-0.0.1-SNAPSHOT.war
  discard-paths: yes
